name: Weekly Billing

on:
  schedule:
    # Every Thursday at 00:00 UTC
    - cron: '0 0 * * 4'

jobs:
  run-billing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run Weekly Provider Bill
        run: node weeklyProvidersBill.js

      - name: Run Weekly Admin Bill
        run: node weeklyAdminProvidersBill.js
